server.shutdown: graceful

spring:
  application.name: send-mail-app
  main.banner_mode: off
  output.ansi.enabled: always
  lifecycle.timeout-per-shutdown-phase: "20s"
  mail:
    #    test-connection: true
    host: "smtp.gmail.com"
    #    port: 587
    username: "jrathod1307@gmail.com"
    password: ""
    properties.mail:
      debug: true
#      transport.protocol: smtp
#      smtp:
#        auth: true
#        host: "jrathod1307@gmail.com"
#        port: 587
#        starttls.enabled: true
